### ISSUE TITLE
Errors (conflict with guzzle)

### ISSUE THREAD

**Issue by atquest** [mollie/mollie-api-php#309]
I'm getting this error:

```
[31-Oct-2018 19:03:00 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function _PhpScoper5bc8350a1bb6a\GuzzleHttp\choose_handler() in /srv/users/xx/apps/xx/public/wp-content/plugins/events-made-easy/payment_gateways/Mollie/2.1.3/vendor/guzzlehttp/guzzle/src/HandlerStack.php:37
Stack trace:
#0 /srv/users/xx/apps/xx/public/wp-content/plugins/events-made-easy/payment_gateways/Mollie/2.1.3/vendor/guzzlehttp/guzzle/src/Client.php(64): _PhpScoper5bc8350a1bb6a\GuzzleHttp\HandlerStack::create()
#1 /srv/users/xx/apps/xx/public/wp-content/plugins/events-made-easy/payment_gateways/Mollie/2.1.3/src/MollieApiClient.php(204): _PhpScoper5bc8350a1bb6a\GuzzleHttp\Client->__construct(Array)
#2 /srv/users/xx/apps/xx/public/wp-content/plugins/events-made-easy/eme_payments.php(786): Mollie\Api\MollieApiClient->__construct()
#3 /srv/users/xx/apps/xx/public/wp-content/plugins/events-made-easy/eme_payments.php(63): eme_mollie_form(Array, Array, 17.5, 'EUR', '', 0)
#4 /srv/users/xx/apps/xx/public/wp-content/plugins/events-made-easy/eme_rsvp.php( in /srv/users/xx/apps/xx/public/wp-content/plugins/events-made-easy/payment_gateways/Mollie/2.1.3/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 37
```

**Comment by willemstuursma** [comment]
Did you use the included autoloader @atquest ?
